version: '3.8'
name: payload
networks:
  coolify:
    name: coolify
    external: true
services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: 'curl -f --head http://127.0.0.1:3000 || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    expose:
      - 3000    
    volumes:
      - node_app:/app
    working_dir: /app/
    networks:
      - coolify
volumes:
  node_app:
labels:
  - 'traefik.http.middlewares.root-to-www.redirectregex.regex=^https?://iact.dev/(.*)'
  - 'traefik.http.middlewares.root-to-www.redirectregex.replacement=https://www.iact.dev/$${1}'
  - 'traefik.http.middlewares.root-to-www.redirectregex.permanent=true'
  - 'traefik.http.routers.root-redirect-router.rule=Host(`iact.dev`)'
  - 'traefik.http.routers.root-redirect-router.entrypoints=https'
  - 'traefik.http.routers.root-redirect-router.middlewares=root-to-www'
  - 'traefik.http.routers.root-redirect-router.tls=true'
  - 'traefik.http.routers.root-redirect-router.tls.certresolver=letsencrypt'