services:
  payload:
    container_name: payload
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    pull_policy: build
    image: custom-payload-website:3.84.1
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    environment:
      - 'NODE_ENV=production'
    healthcheck:
      test: 'curl -f --head http://127.0.0.1:3000 || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    expose:
      - 3000 
    volumes:
      - node_app:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    # command: 'tail -f /dev/null'
    command: 'sh -c "node server.js"'
    labels:
      traefik.enable: true
      coolify.managed: true
      coolify.proxy: true
volumes:
  node_app:
  node_modules:

